# Site settings
title: Reon‘s Blog
header-img: img/home-bg.jpg
email: reondz@gmail.com
description: "Reon Dz"
baseurl: ""
url: "http://reondz.github.io"
github_username:  ReonDz

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
