# Site settings
title: Reon‘s Blog
header-img: img/home-bg.jpg
email: reondz@gmail.com
description: "Reon Dz."
baseurl: ""
url: "http://reondz.github.io"
twitter_username: ReonDz
github_username:  ReonDz
facebook_username:  ReonDz

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
